#!/usr/bin/env node

/**
 * Auto-generate bindings/index.ts from the generated TypeScript files
 *
 * This script scans the bindings/ directory for .ts files (excluding index.ts)
 * and generates an index.ts file that exports all types.
 */

const fs = require('fs');
const path = require('path');

const BINDINGS_DIR = path.join(__dirname, 'bindings');
const INDEX_FILE = path.join(BINDINGS_DIR, 'index.ts');

function generateIndex() {
  // Check if bindings directory exists
  if (!fs.existsSync(BINDINGS_DIR)) {
    console.log('⚠️  bindings/ directory does not exist yet. Skipping index generation.');
    return;
  }

  // Read all .ts files in bindings directory
  const files = fs.readdirSync(BINDINGS_DIR)
    .filter(file => file.endsWith('.ts') && file !== 'index.ts')
    .sort();

  if (files.length === 0) {
    console.log('⚠️  No TypeScript files found in bindings/. Skipping index generation.');
    return;
  }

  // Categorize files based on naming convention
  const dbTypes = files.filter(f => f.startsWith('Db'));
  const contactTypes = files.filter(f => f.startsWith('Contact'));
  const otherTypes = files.filter(f => !f.startsWith('Db') && !f.startsWith('Contact'));

  // Generate index.ts content
  const lines = [
    '// Auto-generated index file - exports all TypeScript types generated from Rust',
    '// Generated by generate-index.js - do not edit manually',
    '',
  ];

  if (dbTypes.length > 0) {
    lines.push('// Database types');
    dbTypes.forEach(file => {
      const typeName = path.basename(file, '.ts');
      lines.push(`export type { ${typeName} } from './${typeName}';`);
    });
    lines.push('');
  }

  if (contactTypes.length > 0) {
    lines.push('// Contact format types');
    contactTypes.forEach(file => {
      const typeName = path.basename(file, '.ts');
      lines.push(`export type { ${typeName} } from './${typeName}';`);
    });
    lines.push('');
  }

  if (otherTypes.length > 0) {
    lines.push('// Other types');
    otherTypes.forEach(file => {
      const typeName = path.basename(file, '.ts');
      lines.push(`export type { ${typeName} } from './${typeName}';`);
    });
    lines.push('');
  }

  // Write index.ts
  const content = lines.join('\n');
  fs.writeFileSync(INDEX_FILE, content, 'utf8');

  console.log(`✅ Generated bindings/index.ts with ${files.length} type exports`);
}

// Run the generator
try {
  generateIndex();
} catch (error) {
  console.error('❌ Error generating index.ts:', error.message);
  process.exit(1);
}
