/**
 * Image imports, so a bundled asset can be `import`ed rather than `require`d.
 *
 * Metro turns `import logo from "./logo.png"` into a registered asset and hands back its
 * numeric id, which is what React Native's `<Image source>` takes. TypeScript has no idea
 * that is happening, so without this an image import is an unresolved module.
 *
 * Declared here rather than relying on `expo-env.d.ts`: that file is generated by the Expo
 * CLI and gitignored, so a fresh clone would not typecheck until someone happened to run
 * the right command.
 */
declare module "*.png" {
  const asset: number;
  export default asset;
}
