FROM node:18-alpine
WORKDIR /workspace

COPY package*.json ./
COPY nx.json ./
COPY tsconfig*.json ./
COPY apps/client-web ./apps/client-web
# COPY libs ./libs

RUN npm ci

EXPOSE 3000
CMD ["npx", "nx", "dev", "client-web"]
