/** The pure reminder engine. The repo-backed half is `@leapsake/reminders/api`,
 *  which this barrel must not re-export (README, "Two entry points"). */
export {
  BELATED_DAYS,
  DISPLAY_WINDOW_DAYS,
  NOTIFICATION_WINDOW_DAYS,
  ONBOARDING_REMINDERS,
  SYSTEM_REMINDER_NAMESPACE,
  duplicatesReminderId,
  getReminderInWindow,
  listNotifiableReminders,
  listRemindersInWindow,
  listSystemReminderTargets,
  materializeReminder,
  onboardingRouteOf,
  partnershipNudgeId,
  regenerateSystemReminders,
  snoozeTargetOf,
} from "./engine.js";
export type {
  HolidayBearerType,
  HolidayOccurrenceCandidate,
  OnboardingReminder,
  OnboardingRoute,
  ReminderEngineDeps,
  ReminderWindowFacts,
  SystemReminderStore,
  SystemReminderTarget,
  UndatedPartnership,
  WindowedReminder,
} from "./engine.js";
